#114765 Added label difference check
ensi-platform/laravel-prometheus pull request #2
Opened 2023-10-17 07:53 UTC by valerialukinykh

if label was added or removed from metric, this metric will be removed and recreated

2023-10-18 06:53 UTC, MsNatali requested changes

2023-10-18 06:53 UTC, MsNatali commented on src/Storage/Redis.php
> +                $labelDiff1 == 0 && $labelDiff2 == 0 ||
Давай не писать вперемешку && и ||, оберни группы условий в скобки

2023-10-18 06:53 UTC, MsNatali commented on src/Storage/Redis.php
> +if tonumber(result) >= tonumber(ARGV[3]) or ARGV[5] == '1' then
правильно ли тут сравнивать именно с единицей? У тебя ниже в функции removeMetricOnLabelDiff идет bool|int ответ. Bool я так понимаю всегда false, если никакое изменение не происходит.
int видимо кол-во удалённых записей из redis.call(DEL). Если внезапно кол-во будет 2, то что?
Может быть стоит на уровне php сводить ответ к только булеву - true или false?

2023-10-18 13:24 UTC, valerialukinykh commented on src/Storage/Redis.php
> +if tonumber(result) >= tonumber(ARGV[3]) or ARGV[5] == '1' then
Поправила, теперь возвращается только bool. lua преобразует true в "1", теперь проверка верная

2023-10-18 13:25 UTC, valerialukinykh commented on src/Storage/Redis.php
> +        $result =  boolval($this->redis->eval(
Поменяла способ удаления метрик - при повторном тестировании обнаружила проблему с типом summary

2023-11-17 09:53 UTC, MsNatali approved these changes

2023-11-17 09:53 UTC, merged